spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/autofix_db
    username: admin
    password: admin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: validate
    show-sql: false
  liquibase:
    change-log: classpath:/db/db.changelog-master.yaml
  security:
    jwt:
      secret: 5pAq6zRyX8bC3dV2wS7gN1mK9jF0hL4tUoP6iBvE3nG8xZaQrY7cW2fA
      tokenExpirationTimeInMinutes: 10000
      securityFilterPath: /auth/**
      allowedOriginLink: http://localhost:3000
app:
  loginPassAuth:
    resetPasswordTokenExpirationTimeInMinutes: 15
    sysAdminFirstName: admin
    sysAdminLastName: admin
    sysAdminEmail: admin@test.pl
    sysAdminPassword: password123
stripe:
    secretKey: sk_test_51QbfvaFQNTESLPVj754XHTMT53D0LSUxKfWyxIAtIDeaawWx3eZFb2Ib3JXFnh5fRaJNKg0auRptFAuqFZmXaCWI00Uq2GAffC